# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the documentation/ directory with Sphinx
sphinx:
  configuration: ./en/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
# formats: all
formats: []

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
  install:
    - requirements: ./en/requirements.txt
    - requirements: ./requirements.txt
  system_packages: true
